# Generated by Django 4.0.5 on 2022-11-25 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('escolaridade', models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20)),
                ('referenciacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('regime', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Misto', 'Misto')], default='Online', max_length=20)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoCare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('0-4', '0-4'), ('5-9', '5-9'), ('10-12', '10-12'), ('12+', '12+')], default='', max_length=20, null=True)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.doenca')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GrupoCog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(default='', max_length=300)),
                ('cotacao', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], max_length=10, null=True)),
                ('numeroSessao', models.IntegerField(blank=True, null=True)),
                ('objetivo', models.TextField(blank=True, max_length=1000, null=True)),
                ('descrição', models.TextField(blank=True, max_length=1000, null=True)),
                ('materiais', models.TextField(blank=True, max_length=1000, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('apresentacao', models.FileField(blank=True, null=True, upload_to='apresentacoes/')),
                ('atividades', models.ManyToManyField(blank=True, to='diario.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('escolaridade', models.CharField(choices=[('Analfabeto(a)', 'Analfabeto(a)'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20)),
                ('residencia', models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=20, null=True)),
                ('situacaoLaboral', models.CharField(blank=True, choices=[('Empregado(a)', 'Empregado(a)'), ('Desempregado(a)', 'Desempregado(a)'), ('Reformado(a)', 'Reformado(a)'), ('Doméstica', 'Doméstica'), ('Estudante', 'Estudante')], default='Reformado(a)', max_length=20, null=True)),
                ('profissaoPrincipal', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('situacaoEconomica', models.CharField(blank=True, choices=[('Muito satisfatória', 'Muito satisfatória'), ('Satisfatória', 'Satisfatória'), ('Pouco satisfatória', 'Pouco satisfatória'), ('Nada satisfatória', 'Nada satisfatória')], default='Satisfatória', max_length=20, null=True)),
                ('estadoCivil', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a) ou a viver como tal', 'Casado(a) ou a viver como tal'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a) ou separado(a)', 'Divorciado(a) ou separado(a)')], default='Solteiro(a)', max_length=30, null=True)),
                ('agregadoFamiliar', models.CharField(blank=True, choices=[('Vive sozinho(a)', 'Vive sozinho(a)'), ('Vive com o cônjuge', 'Vive com o cônjuge'), ('Vive com os filhos', 'Vive com os filhos'), ('Vive com terceiros', 'Vive com terceiros'), ('Vive com o cônjuge e terceiros', 'Vive com o cônjuge e terceiros'), ('Vive com os pais', 'Vive com os pais')], default='Vive sozinho(a)', max_length=35, null=True)),
                ('temFilhos', models.BooleanField(blank=True, default=False, null=True)),
                ('nrFilhos', models.IntegerField(blank=True, default=0, null=True)),
                ('autoAvaliacaoEstadoSaude', models.CharField(blank=True, choices=[('Muito mau', 'Muito mau'), ('Mau', 'Mau'), ('Nem mau nem bom', 'Nem mau nem bom'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], default='Nem mau nem bom', max_length=30, null=True)),
                ('avaliador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cuidadores', models.ManyToManyField(blank=True, related_name='participantes', to='diario.cuidador')),
                ('diagnosticos', models.ManyToManyField(related_name='participantes', to='diario.doenca')),
                ('grupoCog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], default='I', max_length=10, null=True)),
                ('sessao_numero', models.IntegerField(blank=True, default=0, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('texto', models.CharField(max_length=200)),
                ('opcoes', models.ManyToManyField(blank=True, default=None, to='diario.opcao')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numeroSessao', models.IntegerField(blank=True, null=True)),
                ('tema', models.TextField(blank=True, max_length=1000, null=True)),
                ('dinamizadores', models.CharField(blank=True, max_length=1000, null=True)),
                ('componentes', models.CharField(blank=True, max_length=1000, null=True)),
                ('instrumentoAvaliacao', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessaoDoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online'), ('M', 'Misto')], default='P', max_length=20, null=True)),
                ('estado', models.CharField(blank=True, choices=[('PR', 'Por realizar'), ('R', 'Realizado')], default='PR', max_length=20, null=True)),
                ('data', models.DateTimeField(null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diario.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='Respostas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(blank=True, max_length=1, null=True)),
                ('respostas', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('topico', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('continuacaoDe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessao')),
                ('perguntas', models.ManyToManyField(blank=True, default=None, to='diario.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('tipoSessao', models.CharField(blank=True, choices=[('PR', 'Protocolo'), ('CG', 'Cog'), ('CR', 'Care')], default='CR', max_length=20, null=True)),
                ('present', models.BooleanField(default=False)),
                ('faltou', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online')], default='P', max_length=20, null=True)),
                ('withApp', models.BooleanField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='diario.cuidador')),
                ('sessaoDoGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_grupo', to='diario.sessaodogrupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartilhaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partilha', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.cuidador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='referenciacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='ParteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('parte', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.parte')),
                ('sessaoGrupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.sessaodogrupo')),
            ],
        ),
        migrations.AddField(
            model_name='parte',
            name='questionarios',
            field=models.ManyToManyField(blank=True, to='diario.questionario'),
        ),
        migrations.AddField(
            model_name='parte',
            name='sessao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='diario.sessao'),
        ),
        migrations.CreateModel(
            name='NotaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaGrupo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Atividades', 'Atividades'), ('Gerais', 'Gerais'), ('Sessão', 'Sessão')], default='Gerais', max_length=20, null=True)),
                ('tituloNota', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nota', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='diario.cuidador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grupoCare', models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacoesGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupocare')),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='InfoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField()),
                ('realizada', models.BooleanField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.parte')),
            ],
        ),
        migrations.AddField(
            model_name='grupocare',
            name='referenciacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='GrupoAvalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('avaliador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.avaliador')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grupoCog', models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('materiais', models.CharField(blank=True, max_length=1000, null=True)),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], max_length=10, null=True)),
                ('duracao', models.CharField(blank=True, max_length=10, null=True)),
                ('atividade', models.TextField(blank=True, max_length=1000, null=True)),
                ('objetivo', models.TextField(blank=True, max_length=1000, null=True)),
                ('sessoes', models.ManyToManyField(related_name='exercicios', to='diario.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escrita', models.CharField(default='', max_length=750)),
                ('opcao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.opcao')),
                ('parte_grupo', models.ForeignKey(blank=True, default=18, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.partegrupo')),
                ('pergunta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.pergunta')),
                ('sessao_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('utilizador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cuidador', models.ManyToManyField(blank=True, related_name='documents', to='diario.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='DinamizadorConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('funcao', models.CharField(default='', max_length=20)),
                ('grupoCare', models.ManyToManyField(blank=True, related_name='dinamizadores', to='diario.grupocare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuidador',
            name='grupoCare',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.grupocare'),
        ),
        migrations.CreateModel(
            name='Auxiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('grupoCog', models.ManyToManyField(blank=True, related_name='auxiliares', to='diario.grupocog')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
