# Generated by Django 4.0.4 on 2023-05-30 16:45

import diario.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(default=0)),
                ('nome', models.CharField(blank=True, max_length=1000, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('escolaridade', models.CharField(choices=[('Analfabeto', 'Analfabeto'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20)),
                ('regime', models.CharField(choices=[('Online', 'Online'), ('Presencial', 'Presencial'), ('Misto', 'Misto')], default='Online', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Doenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(default='', max_length=100)),
                ('numero', models.IntegerField(default=0)),
                ('duracao', models.CharField(blank=True, max_length=10, null=True)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('material', models.TextField(blank=True, max_length=1000, null=True)),
                ('instrucao', models.TextField(blank=True, max_length=2000, null=True)),
                ('instrucao_participante', models.TextField(blank=True, max_length=2000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='', max_length=20, null=True)),
                ('nivelGDS', models.IntegerField(default=0)),
                ('programa', models.CharField(blank=True, choices=[('CARE', 'CARE'), ('COG', 'COG')], default='CARE', max_length=20, null=True)),
                ('diagnostico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.doenca')),
            ],
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=diario.models.img_path)),
            ],
        ),
        migrations.CreateModel(
            name='InformacaoSensivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Opcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(default='', max_length=300)),
                ('cotacao', models.IntegerField(blank=True, default=0, null=True)),
                ('imagem', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='Parte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], max_length=10, null=True)),
                ('objetivo', models.TextField(blank=True, max_length=1000, null=True)),
                ('descrição', models.TextField(blank=True, max_length=1000, null=True)),
                ('materiais', models.TextField(blank=True, max_length=1000, null=True)),
                ('duracao', models.IntegerField(blank=True, null=True)),
                ('apresentacao', models.FileField(blank=True, null=True, upload_to='apresentacoes/')),
                ('atividades', models.ManyToManyField(blank=True, to='diario.atividade')),
            ],
        ),
        migrations.CreateModel(
            name='Parte_Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ordem', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('duracao', models.IntegerField(default=0)),
                ('imagens', models.ManyToManyField(blank=True, default=None, to='diario.imagem')),
            ],
        ),
        migrations.CreateModel(
            name='ParteGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('exercicio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.exercicio')),
                ('parte', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.parte')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('escolaridade', models.CharField(blank=True, choices=[('Analfabeto(a)', 'Analfabeto(a)'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20)),
                ('residencia', models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=20, null=True)),
                ('situacaoLaboral', models.CharField(blank=True, choices=[('Empregado(a)', 'Empregado(a)'), ('Desempregado(a)', 'Desempregado(a)'), ('Reformado(a)', 'Reformado(a)'), ('Doméstica', 'Doméstica'), ('Estudante', 'Estudante')], default='Reformado(a)', max_length=20, null=True)),
                ('profissaoPrincipal', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('situacaoEconomica', models.CharField(blank=True, choices=[('Muito satisfatória', 'Muito satisfatória'), ('Satisfatória', 'Satisfatória'), ('Pouco satisfatória', 'Pouco satisfatória'), ('Nada satisfatória', 'Nada satisfatória')], default='Satisfatória', max_length=20, null=True)),
                ('estadoCivil', models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a) ou a viver como tal', 'Casado(a) ou a viver como tal'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a) ou separado(a)', 'Divorciado(a) ou separado(a)')], default='Solteiro(a)', max_length=30, null=True)),
                ('agregadoFamiliar', models.CharField(blank=True, choices=[('Vive sozinho(a)', 'Vive sozinho(a)'), ('Vive com o cônjuge', 'Vive com o cônjuge'), ('Vive com os filhos', 'Vive com os filhos'), ('Vive com terceiros', 'Vive com terceiros'), ('Vive com o cônjuge e terceiros', 'Vive com o cônjuge e terceiros'), ('Vive com os pais', 'Vive com os pais')], default='Vive sozinho(a)', max_length=35, null=True)),
                ('temFilhos', models.BooleanField(blank=True, default=False, null=True)),
                ('nrFilhos', models.IntegerField(blank=True, default=0, null=True)),
                ('autoAvaliacaoEstadoSaude', models.CharField(blank=True, choices=[('Muito mau', 'Muito mau'), ('Mau', 'Mau'), ('Nem mau nem bom', 'Nem mau nem bom'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], default='Nem mau nem bom', max_length=30, null=True)),
                ('nivel_gds', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('avaliador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to=settings.AUTH_USER_MODEL)),
                ('cuidadores', models.ManyToManyField(blank=True, related_name='participantes', to='diario.cuidador')),
                ('diagnosticos', models.ManyToManyField(blank=True, default=None, null=True, related_name='participantes', to='diario.doenca')),
                ('grupo', models.ManyToManyField(blank=True, related_name='participantes', to='diario.grupo')),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(blank=True, choices=[('I', 'Inicial'), ('D', 'Desenvolvimento'), ('F', 'Final')], default='I', max_length=10, null=True)),
                ('sessao_numero', models.IntegerField(blank=True, default=0, null=True)),
                ('ordem', models.IntegerField(default=0)),
                ('texto', models.CharField(max_length=200)),
                ('opcoes', models.ManyToManyField(blank=True, default=None, to='diario.opcao')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta_Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('postexto', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('tipo_resposta', models.CharField(choices=[('APENAS_MOSTRAR', 'Apenas Mostrar'), ('UPLOAD_FOTOGRAFIA', 'Upload Fotografia'), ('RESPOSTA_ESCRITA', 'Resposta Escrita'), ('ESCOLHA_MULTIPLA', 'Escolha Múltipla')], max_length=50)),
                ('dificuldade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=20)),
                ('opcoes', models.ManyToManyField(blank=True, default=None, to='diario.opcao')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
                ('numeroSessao', models.IntegerField(blank=True, null=True)),
                ('tema', models.TextField(blank=True, max_length=1000, null=True)),
                ('dinamizadores', models.CharField(blank=True, max_length=1000, null=True)),
                ('componentes', models.CharField(blank=True, max_length=1000, null=True)),
                ('instrumentoAvaliacao', models.TextField(blank=True, max_length=1000, null=True)),
                ('programa', models.CharField(blank=True, choices=[('CARE', 'CARE'), ('COG', 'COG')], default='CARE', max_length=20, null=True)),
                ('materiais', models.FileField(blank=True, null=True, upload_to='materiais/')),
                ('relatorio', models.FileField(blank=True, null=True, upload_to='relatorios/')),
            ],
        ),
        migrations.CreateModel(
            name='SessaoDoGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regime', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online'), ('M', 'Misto')], default='P', max_length=20, null=True)),
                ('estado', models.CharField(blank=True, choices=[('PR', 'Por realizar'), ('EC', 'Em curso'), ('R', 'Realizado')], default='PR', max_length=20, null=True)),
                ('data', models.DateTimeField(null=True)),
                ('inicio', models.DateTimeField(blank=True, null=True)),
                ('fim', models.DateTimeField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
                ('parte_ativa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diario.parte_exercicio')),
                ('sessao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diario.sessao')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escrita', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('resposta_submetida', models.ImageField(blank=True, null=True, upload_to=diario.models.submission_path)),
                ('apontamento', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('certo', models.BooleanField(blank=True, default=None, null=True)),
                ('parte_exercicio', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.parte_exercicio')),
                ('parte_grupo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.partegrupo')),
                ('participante', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
                ('pergunta', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.pergunta_exercicio')),
                ('resposta_escolha', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='diario.opcao')),
                ('sessao_grupo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
        migrations.CreateModel(
            name='Questionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(default='', max_length=50)),
                ('topico', models.CharField(blank=True, default='', max_length=300, null=True)),
                ('continuacaoDe', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessao')),
                ('perguntas', models.ManyToManyField(blank=True, default=None, to='diario.pergunta')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(null=True)),
                ('tipoSessao', models.CharField(blank=True, choices=[('PR', 'Protocolo'), ('CG', 'Cog'), ('CR', 'Care')], default='CR', max_length=20, null=True)),
                ('present', models.BooleanField(default=False)),
                ('faltou', models.BooleanField(default=False)),
                ('mode', models.CharField(blank=True, choices=[('P', 'Presencial'), ('O', 'Online')], default='P', max_length=20, null=True)),
                ('withApp', models.BooleanField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='diario.cuidador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='diario.participante')),
                ('sessaoDoGrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessao_grupo', to='diario.sessaodogrupo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartilhaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Partilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partilha', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.cuidador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.AddField(
            model_name='participante',
            name='referenciacao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.AddField(
            model_name='participante',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partegrupo',
            name='sessaoGrupo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parteGrupos', to='diario.sessaodogrupo'),
        ),
        migrations.AddField(
            model_name='parte_exercicio',
            name='perguntas',
            field=models.ManyToManyField(blank=True, default=None, to='diario.pergunta_exercicio'),
        ),
        migrations.AddField(
            model_name='parte',
            name='questionarios',
            field=models.ManyToManyField(blank=True, to='diario.questionario'),
        ),
        migrations.AddField(
            model_name='parte',
            name='sessao',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partes', to='diario.sessao'),
        ),
        migrations.CreateModel(
            name='NotaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notaGrupo', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('Atividades', 'Atividades'), ('Gerais', 'Gerais'), ('Sessão', 'Sessão')], default='Gerais', max_length=20, null=True)),
                ('tituloNota', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nota', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('cuidador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='diario.cuidador')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('grupo', models.ManyToManyField(blank=True, related_name='mentores', to='diario.grupo')),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformacoesGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='Informacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informacoes', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='InfoParte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracao', models.IntegerField()),
                ('realizada', models.BooleanField()),
                ('parte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.parte')),
            ],
        ),
        migrations.AddField(
            model_name='grupo',
            name='referenciacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('grupo', models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupo')),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='exercicio',
            name='partes_do_exercicio',
            field=models.ManyToManyField(blank=True, related_name='exercicios', to='diario.parte_exercicio'),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='sessao',
            field=models.ManyToManyField(blank=True, default=None, related_name='exercicios', to='diario.sessao'),
        ),
        migrations.CreateModel(
            name='Escolha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escrita', models.CharField(blank=True, default=None, max_length=750, null=True)),
                ('opcao', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.opcao')),
                ('parte_grupo', models.ForeignKey(blank=True, default=18, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.partegrupo')),
                ('pergunta', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='diario.pergunta')),
                ('sessao_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('utilizador', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('cuidador', models.ManyToManyField(blank=True, related_name='documents', to='diario.cuidador')),
            ],
        ),
        migrations.CreateModel(
            name='DinamizadorConvidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('funcao', models.CharField(default='', max_length=20)),
                ('grupo', models.ManyToManyField(blank=True, related_name='dinamizadores', to='diario.grupo')),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cuidador',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.grupo'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='referenciacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='AvaliacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacao_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_materiais', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_tempo', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('grau_dominio', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('necessidade_treino', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=10, null=True)),
                ('apreciacao_global', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('tipo_treino_competencias', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('observacao', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('submetido_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comunicacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('iniciativa', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('satisfacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('humor', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('eficacia_relacional', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('observacao', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('participante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('submetido_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador')),
            ],
        ),
    ]
