# Generated by Django 4.1.1 on 2023-09-13 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PartilhaGrupo',
        ),
    ]
