# Generated by Django 4.0.5 on 2022-12-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte_exercicio',
            name='dificuldade_teste',
        ),
        migrations.AddField(
            model_name='parte_exercicio',
            name='dificuldade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=20),
        ),
    ]
