# Generated by Django 4.0.5 on 2022-11-25 18:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacaoSensivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('telemovel', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='auxiliar',
            name='email',
        ),
        migrations.RemoveField(
            model_name='auxiliar',
            name='image',
        ),
        migrations.RemoveField(
            model_name='auxiliar',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='auxiliar',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='image',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='avaliador',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='image',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='email',
        ),
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='image',
        ),
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='facilitador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='facilitador',
            name='image',
        ),
        migrations.RemoveField(
            model_name='facilitador',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='facilitador',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='email',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='telemovel',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='email',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='image',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='telemovel',
        ),
        migrations.AddField(
            model_name='auxiliar',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dinamizadorconvidado',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mentor',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='participante',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='participante',
            name='avaliador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auxiliar',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='dinamizadorconvidado',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='participante',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
    ]
