# Generated by Django 4.0.5 on 2022-12-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_remove_parte_exercicio_dificuldade_teste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte_exercicio',
            name='imagens',
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
    ]
