# Generated by Django 4.1.1 on 2023-09-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_delete_partilhagrupo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaosessao',
            name='sessao_grupo',
        ),
        migrations.RemoveField(
            model_name='avaliacaosessao',
            name='submetido_por',
        ),
        migrations.DeleteModel(
            name='AvaliacaoParticipante',
        ),
        migrations.DeleteModel(
            name='AvaliacaoSessao',
        ),
    ]
