# Generated by Django 4.1.1 on 2023-09-13 15:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_remove_avaliacaosessao_sessao_grupo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacao_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_materiais', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_tempo', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('grau_dominio', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('necessidade_treino', models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=10, null=True)),
                ('apreciacao_global', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('tipo_treino_competencias', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('observacao', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('submetido_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comunicacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('iniciativa', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('satisfacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('humor', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('eficacia_relacional', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('observacao', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('participante', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
                ('submetido_por', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador')),
            ],
        ),
    ]
