# Generated by Django 4.1.7 on 2023-07-11 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_administrador'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='avaliador',
            old_name='Reference',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='cuidador',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='facilitador',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='participante',
            name='idade',
        ),
        migrations.AddField(
            model_name='parte',
            name='ordem',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='partilha',
            name='ficheiro',
            field=models.FileField(blank=True, null=True, upload_to='ficheiros_partilhas/'),
        ),
        migrations.AddField(
            model_name='partilha',
            name='imagem',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
