# Generated by Django 4.0.5 on 2022-12-02 19:20

import diario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_remove_parte_exercicio_imagens_delete_imagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=diario.models.img_path)),
            ],
        ),
    ]
