# Generated by Django 4.1.1 on 2023-09-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_avaliacaosessao_avaliacaoparticipante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='diagnostico',
        ),
    ]
