# Generated by Django 4.0.5 on 2022-12-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_imagem_parte_exercicio_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercicio',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='dominio',
        ),
        migrations.RemoveField(
            model_name='exercicio',
            name='numero',
        ),
        migrations.CreateModel(
            name='Exercicio_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio', models.CharField(max_length=100)),
                ('numero', models.IntegerField(default=0)),
                ('descricao', models.TextField(blank=True, max_length=1000, null=True)),
                ('material', models.TextField(blank=True, max_length=1000, null=True)),
                ('instrucao', models.TextField(blank=True, max_length=2000, null=True)),
                ('instrucao_participante', models.TextField(blank=True, max_length=2000, null=True)),
                ('duracao', models.CharField(blank=True, max_length=10, null=True)),
                ('partes_do_exercico', models.ManyToManyField(blank=True, to='diario.parte_exercicio')),
                ('sessao', models.ManyToManyField(blank=True, related_name='ex2', to='diario.sessao')),
            ],
        ),
    ]
