# Generated by Django 4.1.1 on 2023-09-22 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_remove_grupo_diagnostico'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartilhaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='images/')),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to='ficheiros_partilhas/')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
                ('partilha_dinamizador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partilha_grupo_dinamizador', to='diario.dinamizadorconvidado')),
                ('partilha_mentor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partilha_grupo_mentor', to='diario.mentor')),
                ('sessao_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
    ]
