# Generated by Django 4.0.5 on 2022-12-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_remove_exercicio_descricao_remove_exercicio_dominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='dominio',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='exercicio',
            name='numero',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Exercicio_2',
        ),
    ]
