# Generated by Django 4.0.5 on 2022-12-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0006_exercicio_descricao_exercicio_dominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercicio',
            name='sessao',
            field=models.ManyToManyField(blank=True, default=None, related_name='exercicios', to='diario.sessao'),
        ),
    ]
