# Generated by Django 4.0.5 on 2022-12-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_remove_exercicio_sessao_exercicio_sessao_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parte_exercicio',
            name='imagens',
            field=models.ManyToManyField(blank=True, default=None, to='diario.imagem'),
        ),
    ]
