# Generated by Django 4.1.1 on 2023-10-31 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0007_colaborador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Colaborador',
        ),
    ]
