# Generated by Django 4.0.5 on 2022-12-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0008_parte_exercicio_imagens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partegrupo',
            name='exercicio',
        ),
        migrations.AddField(
            model_name='partegrupo',
            name='exercicio_2',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.exercicio'),
        ),
    ]
