# Generated by Django 4.1.1 on 2024-02-04 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0008_delete_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacaosensivel',
            name='telemovel',
            field=models.CharField(blank=True, default='987654321', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('localizacao', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
                ('reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
