# Generated by Django 4.1.1 on 2024-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_alter_informacaosensivel_telemovel_colaborador'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='dadosCuidador',
            field=models.CharField(blank=True, choices=[('Cuidador', 'Cuidador'), ('Participante', 'Participante'), ('Familiar', 'Familiar')], default='Participante', max_length=20, null=True),
        ),
    ]
