# Generated by Django 4.0.5 on 2022-12-02 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_remove_partegrupo_exercicio_partegrupo_exercicio_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partegrupo',
            old_name='exercicio_2',
            new_name='exercicio',
        ),
    ]
