# Generated by Django 4.0.5 on 2022-12-02 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_rename_exercicio_2_partegrupo_exercicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partegrupo',
            name='parte',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partesGrupos', to='diario.parte'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='nome',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
