# Generated by Django 4.1.1 on 2024-02-27 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_participante_dadoscuidador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='dadosCuidador',
        ),
    ]
