# Generated by Django 4.0.5 on 2022-12-07 15:27

import diario.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_alter_partegrupo_parte_alter_sessao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagem_2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=diario.models.img_path)),
            ],
        ),
        migrations.DeleteModel(
            name='Imagem',
        ),
        migrations.AlterField(
            model_name='parte_exercicio',
            name='imagens',
            field=models.ManyToManyField(blank=True, default=None, to='diario.imagem_2'),
        ),
    ]
