# Generated by Django 4.1.1 on 2024-03-10 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0011_remove_participante_dadoscuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='participante',
            name='dadosCuidador',
            field=models.CharField(blank=True, choices=[('Cuidador', 'Cuidador'), ('Participante', 'Participante'), ('Familiar', 'Familiar')], default='Participante', max_length=20, null=True),
        ),
    ]
