# Generated by Django 4.1.1 on 2024-03-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_participante_dadoscuidador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='comorbilidades',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diagnosticoPrincipal',
            field=models.CharField(blank=True, choices=[('Bipolar', 'Bipolar'), ('Demência', 'Demência'), ('Depressão Maior', 'Depressão Maior'), ('Doença Mental', 'Doença Mental'), ('Epilepsia', 'Epilepsia'), ('Esquizofrenia', 'Esquizofrenia'), ('Incapacidade Inteletual', 'Incapacidade Inteletual'), ('Nada (hiperatividade)', 'Nada (hiperatividade)'), ('Perturbação Bipolar', 'Perturbação Bipolar'), ('Não tem', 'Outra')], default='Alzheimer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='comorbilidades',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='diagnosticoPrincipal',
            field=models.CharField(blank=True, choices=[('Bipolar', 'Bipolar'), ('Demência', 'Demência'), ('Depressão Maior', 'Depressão Maior'), ('Doença Mental', 'Doença Mental'), ('Epilepsia', 'Epilepsia'), ('Esquizofrenia', 'Esquizofrenia'), ('Incapacidade Inteletual', 'Incapacidade Inteletual'), ('Nada (hiperatividade)', 'Nada (hiperatividade)'), ('Perturbação Bipolar', 'Perturbação Bipolar'), ('Não tem', 'Outra')], default='Alzheimer', max_length=2000, null=True),
        ),
    ]
