# Generated by Django 4.0.5 on 2022-12-07 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0012_imagem_2_delete_imagem_alter_parte_exercicio_imagens'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Imagem_2',
            new_name='Imagem',
        ),
    ]
