# Generated by Django 4.0.5 on 2022-12-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0013_rename_imagem_2_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercicio',
            old_name='partes_do_exercico',
            new_name='partes_do_exercicio',
        ),
    ]
