# Generated by Django 4.0.5 on 2022-12-09 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0014_rename_partes_do_exercico_exercicio_partes_do_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessaodogrupo',
            name='parte_ativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diario.parte_exercicio'),
        ),
    ]
