# Generated by Django 4.0.1 on 2022-12-14 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0015_sessaodogrupo_parte_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidador',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='cuidadores', to='diario.Grupo'),
        ),
        migrations.AlterField(
            model_name='dinamizadorconvidado',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='dinamizadores', to='diario.Grupo'),
        ),
        migrations.AlterField(
            model_name='documents',
            name='cuidador',
            field=models.ManyToManyField(blank=True, related_name='documents', to='diario.Cuidador'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='partes_do_exercicio',
            field=models.ManyToManyField(blank=True, related_name='exercicios', to='diario.Parte_Exercicio'),
        ),
        migrations.AlterField(
            model_name='exercicio',
            name='sessao',
            field=models.ManyToManyField(blank=True, default=None, related_name='exercicios', to='diario.Sessao'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='grupo',
            field=models.ManyToManyField(blank=True, related_name='mentores', to='diario.Grupo'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='atividades',
            field=models.ManyToManyField(blank=True, to='diario.Atividade'),
        ),
        migrations.AlterField(
            model_name='parte',
            name='questionarios',
            field=models.ManyToManyField(blank=True, to='diario.Questionario'),
        ),
        migrations.AlterField(
            model_name='parte_exercicio',
            name='perguntas',
            field=models.ManyToManyField(blank=True, default=None, to='diario.Pergunta'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='cuidadores',
            field=models.ManyToManyField(blank=True, related_name='participantes', to='diario.Cuidador'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='diagnosticos',
            field=models.ManyToManyField(related_name='participantes', to='diario.Doenca'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='opcoes',
            field=models.ManyToManyField(blank=True, default=None, to='diario.Opcao'),
        ),
        migrations.AlterField(
            model_name='questionario',
            name='perguntas',
            field=models.ManyToManyField(blank=True, default=None, to='diario.Pergunta'),
        ),
    ]
