# Generated by Django 4.0.1 on 2022-12-16 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0016_alter_cuidador_grupo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informacaosensivel',
            old_name='image',
            new_name='imagem',
        ),
    ]
