# Generated by Django 4.0.3 on 2022-12-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0017_rename_image_informacaosensivel_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parte_exercicio',
            name='perguntas',
            field=models.ManyToManyField(blank=True, default=None, to='diario.pergunta_exercicio'),
        ),
        migrations.AlterField(
            model_name='pergunta_exercicio',
            name='tipo_resposta',
            field=models.CharField(choices=[('APENAS_MOSTRAR', 'Apenas Mostrar'), ('UPLOAD_FOTOGRAFIA', 'Upload Fotografia')], max_length=50),
        ),
    ]
