# Generated by Django 4.0.1 on 2022-12-27 19:54

import diario.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0018_alter_parte_exercicio_perguntas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_escrita', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('resposta_submetida', models.ImageField(blank=True, null=True, upload_to=diario.models.submission_path)),
                ('apontamento', models.TextField(blank=True, default=None, max_length=2000, null=True)),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('parte_grupo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.partegrupo')),
                ('participante', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
                ('pergunta', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.pergunta_exercicio')),
                ('sessao_grupo', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
        migrations.AlterField(
            model_name='parte_exercicio',
            name='perguntas',
            field=models.ManyToManyField(blank=True, default=None, to='diario.Pergunta_Exercicio'),
        ),
        migrations.DeleteModel(
            name='Respostas',
        ),
    ]
