# Generated by Django 4.0.1 on 2022-12-28 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0019_resposta_alter_parte_exercicio_perguntas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='certo',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pergunta_exercicio',
            name='tipo_resposta',
            field=models.CharField(choices=[('APENAS_MOSTRAR', 'Apenas Mostrar'), ('UPLOAD_FOTOGRAFIA', 'Upload Fotografia'), ('RESPOSTA_ESCRITA', 'Resposta Escrita')], max_length=50),
        ),
    ]
