# Generated by Django 4.0.1 on 2023-01-05 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0020_resposta_certo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parte_exercicio',
            name='dificuldade',
        ),
        migrations.AddField(
            model_name='pergunta_exercicio',
            name='dificuldade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default='A', max_length=20),
        ),
        migrations.AlterField(
            model_name='partegrupo',
            name='sessaoGrupo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='parteGrupos', to='diario.sessaodogrupo'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='participantes', to='diario.Doenca'),
        ),
        migrations.AlterField(
            model_name='participante',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('Analfabeto(a)', 'Analfabeto(a)'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='1-4', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='referenciacao',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
    ]
