# Generated by Django 4.0.3 on 2023-01-05 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0021_remove_parte_exercicio_dificuldade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta_exercicio',
            name='opcoes',
            field=models.ManyToManyField(blank=True, default=None, to='diario.opcao'),
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta_escolha',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resp', to='diario.opcao'),
        ),
        migrations.AlterField(
            model_name='pergunta_exercicio',
            name='tipo_resposta',
            field=models.CharField(choices=[('APENAS_MOSTRAR', 'Apenas Mostrar'), ('UPLOAD_FOTOGRAFIA', 'Upload Fotografia'), ('RESPOSTA_ESCRITA', 'Resposta Escrita'), ('ESCOLHA_MULTIPLA', 'Escolha Múltipla')], max_length=50),
        ),
    ]
