# Generated by Django 4.0.3 on 2023-01-05 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0022_pergunta_exercicio_opcoes_resposta_resposta_escolha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opcao',
            name='imagem',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.imagem'),
        ),
        migrations.AlterField(
            model_name='pergunta_exercicio',
            name='dificuldade',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('Indefinido', 'Indefinido')], default='Indefinido', max_length=20),
        ),
    ]
