# Generated by Django 4.0.3 on 2023-01-05 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0023_opcao_imagem_alter_pergunta_exercicio_dificuldade'),
    ]

    operations = [
        migrations.AddField(
            model_name='resposta',
            name='parte_exercicio',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.parte_exercicio'),
        ),
    ]
