# Generated by Django 4.0.3 on 2023-01-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0024_resposta_parte_exercicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pergunta_exercicio',
            name='postexto',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
