# Generated by Django 4.0.3 on 2023-01-05 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0025_pergunta_exercicio_postexto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pergunta_exercicio',
            name='nome',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
