# Generated by Django 4.0.3 on 2023-01-09 20:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0026_alter_pergunta_exercicio_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoParticipante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('comunicacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('iniciativa', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('satisfacao', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('humor', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('eficacia_relacional', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('participant', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
    ]
