# Generated by Django 4.0.3 on 2023-01-09 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0027_avaliacaoparticipante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avaliacaoparticipante',
            old_name='participant',
            new_name='participante',
        ),
    ]
