# Generated by Django 4.0.3 on 2023-01-10 07:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0028_rename_participant_avaliacaoparticipante_participante'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoparticipante',
            name='observacao',
            field=models.TextField(blank=True, default='', max_length=550, null=True),
        ),
        migrations.CreateModel(
            name='AvaliacaoSessao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planificacao_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_conteudos', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_materiais', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('adq_tempo', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('grau_dominio', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('necessidade_treino', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('apreciacao_global', models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('tipo_treino_competencias', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('observacao', models.TextField(blank=True, default='', max_length=550, null=True)),
                ('sessao_grupo', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
    ]
