# Generated by Django 4.0.3 on 2023-01-10 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0029_avaliacaoparticipante_observacao_avaliacaosessao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facilitador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20)),
                ('idade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True, null=True)),
                ('nacionalidade', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('grupo', models.ManyToManyField(blank=True, related_name='facilitadores', to='diario.grupo')),
                ('info_sensivel', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
