# Generated by Django 4.0.3 on 2023-01-10 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0030_facilitador'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoparticipante',
            name='submetido_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador'),
        ),
        migrations.AddField(
            model_name='avaliacaosessao',
            name='submetido_por',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.facilitador'),
        ),
    ]
