# Generated by Django 4.0.3 on 2023-01-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0031_avaliacaoparticipante_submetido_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participante',
            name='grupo',
        ),
        migrations.AddField(
            model_name='participante',
            name='grupo_2',
            field=models.ManyToManyField(blank=True, related_name='participantes', to='diario.grupo'),
        ),
    ]
