# Generated by Django 4.0.3 on 2023-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0033_remove_participante_grupo_2_participante_grupo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacaosessao',
            name='necessidade_treino',
            field=models.CharField(blank=True, choices=[('Sim', 'SIM'), ('Não', 'NAO')], default='NAO', max_length=10, null=True),
        ),
    ]
