# Generated by Django 4.0.3 on 2023-01-14 05:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0034_alter_avaliacaosessao_necessidade_treino'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinamizadorconvidado',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='facilitador',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='participante',
            name='nivel_gds',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='avaliacaosessao',
            name='necessidade_treino',
            field=models.CharField(blank=True, choices=[('SIM', 'Sim'), ('NAO', 'Não')], default='NAO', max_length=10, null=True),
        ),
    ]
