# Generated by Django 4.1.7 on 2023-05-30 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0035_dinamizadorconvidado_localizacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessao',
            name='materiais',
            field=models.FileField(blank=True, null=True, upload_to='materiais/'),
        ),
        migrations.AddField(
            model_name='sessao',
            name='relatorio',
            field=models.FileField(blank=True, null=True, upload_to='relatorios/'),
        ),
        migrations.AlterField(
            model_name='cuidador',
            name='referenciacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.AlterField(
            model_name='escolha',
            name='pergunta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='escolhas', to='diario.pergunta'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='escolaridade',
            field=models.CharField(blank=True, choices=[('Analfabeto', 'Analfabeto'), ('1-4', '1-4'), ('5-10', '5-10'), ('11+', '11+')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='sessaodogrupo',
            name='estado',
            field=models.CharField(blank=True, choices=[('PR', 'Por realizar'), ('EC', 'Em curso'), ('R', 'Realizado')], default='PR', max_length=20, null=True),
        ),
    ]
