# Generated by Django 4.2.3 on 2023-07-11 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0003_administrador'),
        ('diario', '0036_sessao_materiais_sessao_relatorio_and_more'),
    ]

    operations = [
    ]
