# Generated by Django 4.1.7 on 2023-07-28 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doenca',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='cuidador',
            name='agregadoFamiliar',
            field=models.CharField(blank=True, choices=[('Vive sozinho(a)', 'Vive sozinho(a)'), ('Vive com o cônjuge', 'Vive com o cônjuge'), ('Vive com os filhos', 'Vive com os filhos'), ('Vive com terceiros', 'Vive com terceiros'), ('Vive com o cônjuge e terceiros', 'Vive com o cônjuge e terceiros'), ('Vive com os pais', 'Vive com os pais')], default='Vive sozinho(a)', max_length=35, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='autoAvaliacaoEstadoSaude',
            field=models.CharField(blank=True, choices=[('Muito mau', 'Muito mau'), ('Mau', 'Mau'), ('Nem mau nem bom', 'Nem mau nem bom'), ('Bom', 'Bom'), ('Muito bom', 'Muito bom')], default='Nem mau nem bom', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasDormir_minutos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasSupervisao_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasSupervisao_minutos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasTarefasCasa_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasTarefasCasa_minutos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasTarefasWC_dias',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diaNormal30DiasTarefasWC_minutos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, default=None, null=True, related_name='cuidadores', to='diario.doenca'),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='estadoCivil',
            field=models.CharField(blank=True, choices=[('Solteiro(a)', 'Solteiro(a)'), ('Casado(a) ou a viver como tal', 'Casado(a) ou a viver como tal'), ('Viúvo(a)', 'Viúvo(a)'), ('Divorciado(a) ou separado(a)', 'Divorciado(a) ou separado(a)')], default='Solteiro(a)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='motivoDependecia',
            field=models.CharField(blank=True, choices=[('Demência/Doença Neurocognitiva (cognitiva adquirida)', 'Demência/Doença Neurocognitiva (cognitiva adquirida)'), ('Deficiência Intelectual (cognitiva congénita)', 'Deficiência Intelectual (cognitiva congénita)'), ('Doença do foro psicológico (emocional/psiquiátrica)', 'Doença do foro psicológico (emocional/psiquiátrica)')], default='Demência/Doença Neurocognitiva (cognitiva adquirida)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='nivelContribuicao',
            field=models.CharField(blank=True, choices=[('1%-20%', '1%-20%'), ('21%-40%', '21%-40%'), ('41%-60%', '41%-60%'), ('61%-80%', '61%-80%'), ('81%-100%', '81%-100%')], default='1%-20%', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='nrFilhos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='periodicidadeCuidado',
            field=models.CharField(blank=True, choices=[('Sempre, excepto em situações esporádicas', 'Sempre, excepto em situações esporádicas'), ('Durante a semana (normalmente de 2ª feira a 6ª feira)', 'Durante a semana (normalmente de 2ª feira a 6ª feira)'), ('Fins de semana (ou período entre os 2-3 dias /semana)', 'Fins de semana (ou período entre os 2-3 dias /semana)'), ('Rotativo (a meses)', 'Rotativo (a meses)'), ('Durante o final da tarde e/ou noite', 'Durante o final da tarde e/ou noite'), ('Pontualmente (1 ou 2 vezes por mês)', 'Pontualmente (1 ou 2 vezes por mês)'), ('Período de férias', 'Período de férias'), ('Outro', 'Outro')], default='Demência/Doença Neurocognitiva (cognitiva adquirida)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosAmigos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosFamiliares',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosOutros',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosProfissionaisCD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosProfissionaisSAD',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='prestadoresCuidadosVizinhos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='principalMotivoParaCuidar',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='profissaoPrincipal',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='residencia',
            field=models.CharField(blank=True, choices=[('Urbana', 'Urbana'), ('Rural', 'Rural')], default='Urbana', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='situacaoEconomica',
            field=models.CharField(blank=True, choices=[('Muito satisfatória', 'Muito satisfatória'), ('Satisfatória', 'Satisfatória'), ('Pouco satisfatória', 'Pouco satisfatória'), ('Nada satisfatória', 'Nada satisfatória')], default='Satisfatória', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='situacaoLaboral',
            field=models.CharField(blank=True, choices=[('Empregado(a)', 'Empregado(a)'), ('Desempregado(a)', 'Desempregado(a)'), ('Reformado(a)', 'Reformado(a)'), ('Doméstica', 'Doméstica'), ('Estudante', 'Estudante')], default='Reformado(a)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='temFilhos',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='tempoCuidados_meses',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='cuidador',
            name='viveComParticipante',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Sim', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dinamizadorconvidado',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='programa',
            field=models.CharField(blank=True, choices=[('CARE', 'CARE'), ('COG', 'COG'), ('GAM', 'GAM')], default='CARE', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sessaodogrupo',
            name='grupo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessoes', to='diario.grupo'),
        ),
    ]
