# Generated by Django 4.1.7 on 2023-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0002_alter_doenca_options_cuidador_agregadofamiliar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinamizadorconvidado',
            name='reference',
        ),
    ]
