# Generated by Django 4.1.7 on 2023-07-28 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0004_dinamizadorconvidado_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='reference',
        ),
    ]
