# Generated by Django 4.1.7 on 2023-07-28 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0005_remove_mentor_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='reference',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
    ]
