# Generated by Django 4.1.7 on 2023-08-03 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0006_mentor_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avaliacaosessao',
            name='sessao_grupo',
        ),
        migrations.RemoveField(
            model_name='avaliacaosessao',
            name='submetido_por',
        ),
        migrations.RemoveField(
            model_name='infoparte',
            name='parte',
        ),
        migrations.RemoveField(
            model_name='informacoes',
            name='participante',
        ),
        migrations.RemoveField(
            model_name='informacoesgrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='partilhagrupo',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='partilhagrupo',
            name='partilha_dinamizador',
        ),
        migrations.RemoveField(
            model_name='partilhagrupo',
            name='partilha_mentor',
        ),
        migrations.RemoveField(
            model_name='partilhagrupo',
            name='sessao_grupo',
        ),
        migrations.AddField(
            model_name='cuidador',
            name='avaliador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parte',
            name='apresentacao_demencia',
            field=models.FileField(blank=True, null=True, upload_to='apresentacao_demencia/'),
        ),
        migrations.AddField(
            model_name='parte',
            name='apresentacao_esquizofrenia',
            field=models.FileField(blank=True, null=True, upload_to='apresentacao_esquizofrenia/'),
        ),
        migrations.AddField(
            model_name='parte',
            name='apresentacao_incapacidade_intelectual',
            field=models.FileField(blank=True, null=True, upload_to='apresentacao_incapacidade_intelectual/'),
        ),
        migrations.AddField(
            model_name='parte',
            name='apresentacao_perturbacao_bipolar',
            field=models.FileField(blank=True, null=True, upload_to='apresentacao_perturbacao_bipolar/'),
        ),
        migrations.DeleteModel(
            name='AvaliacaoParticipante',
        ),
        migrations.DeleteModel(
            name='AvaliacaoSessao',
        ),
        migrations.DeleteModel(
            name='InfoParte',
        ),
        migrations.DeleteModel(
            name='Informacoes',
        ),
        migrations.DeleteModel(
            name='InformacoesGrupo',
        ),
        migrations.DeleteModel(
            name='PartilhaGrupo',
        ),
    ]
