# Generated by Django 4.1.7 on 2023-08-03 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diario', '0008_remove_cuidador_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidador',
            name='avaliador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cuidadores', to=settings.AUTH_USER_MODEL),
        ),
    ]
