# Generated by Django 4.1.7 on 2023-09-12 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0009_cuidador_avaliador'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliador',
            name='data_entrada',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='info_sensivel',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.informacaosensivel'),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='localizacao',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='nacionalidade',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='avaliador',
            name='sexo',
            field=models.CharField(choices=[('Feminino', 'Feminino'), ('Masculino', 'Masculino'), ('Outros', 'Outros')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='participante',
            name='referenciacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.reference'),
        ),
        migrations.CreateModel(
            name='PartilhaGrupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
                ('imagem', models.FileField(blank=True, null=True, upload_to='images/')),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to='ficheiros_partilhas/')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diario.grupo')),
                ('partilha_dinamizador', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partilha_grupo_dinamizador', to='diario.dinamizadorconvidado')),
                ('partilha_mentor', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partilha_grupo_mentor', to='diario.mentor')),
                ('sessao_grupo', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.sessaodogrupo')),
            ],
        ),
    ]
