# Generated by Django 4.1.7 on 2023-09-12 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario', '0010_avaliador_data_entrada_avaliador_info_sensivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partilha',
            name='aprovada',
            field=models.BooleanField(default=False),
        ),
    ]
