# Generated by Django 4.0.4 on 2023-05-30 16:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import protocolo.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('diario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_answer', models.TextField(blank=True, max_length=1000)),
                ('submitted_answer', models.ImageField(blank=True, null=True, upload_to=protocolo.models.resolution_path)),
                ('quotation', models.IntegerField(blank=True, default=0, null=True)),
                ('notes', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('part_number', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParteDoUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parteDoUtilizador', to='protocolo.part')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parteDoUtilizador', to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='PossibleAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('quotation', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='possible_answers_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000)),
                ('image', models.ImageField(blank=True, default=None, upload_to='helping_images/')),
            ],
        ),
        migrations.CreateModel(
            name='TextInputAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seconds', models.IntegerField(blank=True, default=0, null=True)),
                ('text', models.TextField(blank=True, max_length=1000, null=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='TIAnswer', to='protocolo.answer')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.dimension')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idade', models.PositiveIntegerField(default=0)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=10)),
                ('peso', models.FloatField(default=0)),
                ('altura', models.CharField(blank=True, max_length=10)),
                ('imc', models.IntegerField(default=0)),
                ('pressao_arterial', models.IntegerField(default=0)),
                ('colestrol_total', models.FloatField(default=0)),
                ('colestrol_hdl', models.IntegerField(default=0)),
                ('colestrol_nao_hdl', models.IntegerField(default=0)),
                ('hemoglobina_gliciada', models.IntegerField(default=0)),
                ('fumador', models.CharField(choices=[('smoking', 'smoking'), ('nonSmoking', 'nonSmoking')], max_length=10, null=True)),
                ('diabetes', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('anos_diabetes', models.IntegerField(blank=True, default=0)),
                ('avc', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('enfarte', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('doenca_rins', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('doenca_pernas', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('hipercolestrol', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10)),
                ('data_atual', models.DateField(default=django.utils.timezone.now)),
                ('comentario2', models.CharField(blank=True, max_length=200)),
                ('comentario', models.CharField(blank=True, max_length=200)),
                ('risco_de_enfarte', models.IntegerField(default=0, null=True)),
                ('parteDoUtilizador', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.partedoutilizador')),
            ],
            options={
                'db_table': 'protocolo_risk',
            },
        ),
        migrations.CreateModel(
            name='Resolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('statistics', models.JSONField(blank=True, default=dict)),
                ('doctor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.partedoutilizador')),
                ('patient', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.participante')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('question_type', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('instruction', models.TextField(blank=True, max_length=1000)),
                ('quotation_max', models.IntegerField(default=10)),
                ('quotation_min', models.IntegerField(default=0)),
                ('pdf_page', models.IntegerField(default=0)),
                ('helping_images', models.ManyToManyField(blank=True, default=None, related_name='images', to='protocolo.questionimage')),
                ('possible_answers', models.ManyToManyField(blank=True, default=None, related_name='possible_answers', to='protocolo.possibleanswer')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='part',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.protocol'),
        ),
        migrations.CreateModel(
            name='MultipleChoicesCheckbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='MCCAnswer', to='protocolo.answer')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CheckBoxChoice', to='protocolo.possibleanswer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('order', models.IntegerField(default=0)),
                ('tooltip', models.TextField(blank=True, default='', max_length=3500)),
                ('area', models.ManyToManyField(blank=True, default=None, related_name='instruments', to='protocolo.area')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dimension',
            name='instrument',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.instrument'),
        ),
        migrations.AddField(
            model_name='area',
            name='part',
            field=models.ManyToManyField(default=None, related_name='areas', to='protocolo.part'),
        ),
        migrations.AddField(
            model_name='answer',
            name='multiple_choice_answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='protocolo.possibleanswer'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.question'),
        ),
        migrations.AddField(
            model_name='answer',
            name='resolution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='protocolo.resolution'),
        ),
    ]
