# Generated by Django 4.1.1 on 2023-07-17 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='batimentos',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='batimentos2',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='cholhdl',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='cholhdl2',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ldl',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ldl2',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='tg',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='tg2',
        ),
    ]
