# Generated by Django 4.0.4 on 2023-06-13 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='relatorio_word',
        ),
    ]
