# Generated by Django 4.1.1 on 2023-07-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_remove_risk_batimentos_remove_risk_batimentos2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='batimentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='cholhdl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ldl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='tg',
            field=models.IntegerField(default=0),
        ),
    ]
