# Generated by Django 4.0.4 on 2023-06-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0002_remove_risk_relatorio_word'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='relatorio_word',
            field=models.FileField(blank=True, null=True, upload_to='relatorio_risk_word/'),
        ),
    ]
