# Generated by Django 4.1.1 on 2023-07-17 18:12


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0003_risk_batimentos_risk_cholhdl_risk_ldl_risk_tg'),
    ]



    operations = [
        migrations.AddField(
            model_name='risk',
            name='batimentos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='cholhdl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ldl',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='tg',
            field=models.IntegerField(default=0),
        ),
    ]
