# Generated by Django 4.1.1 on 2023-07-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0004_remove_risk_batimentos_remove_risk_cholhdl_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='ac_gnosias_quotation',
            new_name='ac_abstracao_verbal_quotation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ac_proverbios_quotation',
            new_name='ac_atencao_dividida_quotation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ac_tmt_a_quotation',
            new_name='ac_atencao_mantida_quotation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ac_tmt_b_quotation',
            new_name='ac_compreensao_instrucoes_quotation',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='ac_token_test_quotation',
            new_name='ac_orientacao_esq_dir_quotation',
        ),
        migrations.AddField(
            model_name='report',
            name='word',
            field=models.FileField(blank=True, null=True, upload_to='relatorio_eval_word/'),
        ),
    ]
