# Generated by Django 4.1.1 on 2023-08-03 16:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0005_rename_ac_gnosias_quotation_report_ac_abstracao_verbal_quotation_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='dimension',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='instrument',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='multiplechoicescheckbox',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='part',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='possibleanswer',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='protocol',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id', 'order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['id', 'order']},
        ),
        migrations.RemoveField(
            model_name='partedoutilizador',
            name='relatorio',
        ),
        migrations.AddField(
            model_name='part',
            name='caderno_estimulos',
            field=models.FileField(blank=True, default=None, null=True, upload_to='caderno_estimulos/'),
        ),
        migrations.AddField(
            model_name='partedoutilizador',
            name='cuidador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parteDoUtilizador', to='diario.cuidador'),
        ),
        migrations.AddField(
            model_name='report',
            name='json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resolution',
            name='cuidador',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='diario.cuidador'),
        ),
        migrations.AlterField(
            model_name='partedoutilizador',
            name='participante',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parteDoUtilizador', to='diario.participante'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(13)]),
        ),
    ]
