# Generated by Django 4.1.1 on 2023-09-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0006_alter_area_options_alter_dimension_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='cholhdl',
            field=models.FloatField(default=0),
        ),
    ]
