# Generated by Django 4.1.1 on 2024-01-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0007_alter_risk_cholhdl'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='doenca_cognitiva',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='risk',
            name='eag',
            field=models.FloatField(default=68.0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ifcc',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ngsp',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='risk',
            name='pre_diabetico',
            field=models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='risk',
            name='recomendacoes',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='risk',
            name='diabetes',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='horas_jejum',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
