# Generated by Django 4.1.1 on 2024-02-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0008_risk_doenca_cognitiva_risk_eag_risk_ifcc_risk_ngsp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='eag',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ifcc',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ngsp',
        ),
        migrations.AddField(
            model_name='risk',
            name='eag_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ifcc_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ngsp_hba1',
            field=models.FloatField(default=0),
        ),
    ]
