# Generated by Django 4.1.1 on 2024-02-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0009_remove_risk_eag_remove_risk_ifcc_remove_risk_ngsp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='eag_hba1',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ifcc_hba1',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ngsp_hba1',
        ),
        migrations.AddField(
            model_name='risk',
            name='eag',
            field=models.FloatField(default=68.0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ifcc',
            field=models.FloatField(default=20.0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ngsp',
            field=models.IntegerField(default=4),
        ),
    ]
