# Generated by Django 4.1.1 on 2024-03-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0010_remove_risk_eag_hba1_remove_risk_ifcc_hba1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='eag',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ifcc',
        ),
        migrations.RemoveField(
            model_name='risk',
            name='ngsp',
        ),
        migrations.AddField(
            model_name='risk',
            name='eag_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ifcc_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='ngsp_hba1',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='risk',
            name='pergunta_cardiovascular',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Elevado', 'Elevado')], default='Alto', max_length=10),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pre_diabetico',
            field=models.BooleanField(default=False),
        ),
    ]
