# Generated by Django 4.1.1 on 2024-04-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0011_remove_risk_eag_remove_risk_ifcc_remove_risk_ngsp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='fumador',
            field=models.CharField(choices=[('smoking', 'smoking'), ('nonSmoking', 'nonSmoking'), ('exSmoker', 'exSmoker'), ('naoSeSabe', 'naoSeSabe')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='risk',
            name='pergunta_cardiovascular',
            field=models.CharField(choices=[('Baixo', 'Baixo'), ('Moderado', 'Moderado'), ('Alto', 'Alto'), ('Elevado', 'Elevado'), ('Não se sabe', 'Não se sabe')], default='Não se sabe', max_length=100),
        ),
    ]
