# Generated by Django 4.1.1 on 2024-05-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0012_alter_risk_fumador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='pat_id_v2',
            field=models.CharField(blank=True, default=0, max_length=100),
        ),
    ]
