# Generated by Django 4.1.1 on 2024-06-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('protocolo', '0013_risk_pat_id_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='pressao_arterial_diastolica',
            field=models.IntegerField(default=0),
        ),
    ]
