# Generated by Django 4.0.4 on 2023-05-30 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.IntegerField(blank=True, null=True)),
                ('referenciacao', models.CharField(blank=True, choices=[('ADEB', 'ADEB'), ('ASMAL', 'ASMAL'), ('Elo Social', 'Elo Social'), ('CVP', 'CVP'), ('FamiliarMente', 'FamiliarMente'), ('GIRA', 'GIRA')], max_length=30)),
                ('distrito', models.CharField(blank=True, max_length=30)),
                ('assunto', models.CharField(max_length=50)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=125)),
                ('texto', models.TextField()),
                ('data', models.DateField(null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='mentha/noticias/')),
            ],
        ),
    ]
